config/routes.rb
Rails.application.routes.draw do
  root to: "subs#index"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  
  resources :posts, except: [:index, :upvote, :downvote] do
    resources :comments, only: :new
    post "upvote", on: :member
    post "downvote", on: :member
  end
  
  resources :comments, only: [:show, :create, :destroy, :edit, :update] do
    post "upvote", on: :member
    post "downvote", on: :member
  end
  
  get 'static_pages/home'
  get 'static_pages/contact' 
  get 'static_pages/about'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  include Votable
  
  validates :content, :author, :post, presence: true
  belongs_to :post
  belongs_to :author, class_name: "User"
  belongs_to :parent_comment, class_name: "Comment"
  has_many( 
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id
  )
  
  def child_comments_by_parent_id
    Post.find(self.post_id).comments_by_parent_id
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include VotableActions
  
  before_action :require_login, except: :show
  
  def show
    @comment = Comment.find(params[:id])
    render :show
  end
  
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    post_id = params[:comment][:post_id]
    if @comment.save
      redirect_to params[:comment][:redirect]
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to request.referrer
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to params[:comment][:redirect]
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to request.referrer
    end
  end

  def destroy
    comment = Comment.find(:id)
    post_id = comment.post_id
    comment.destroy
    redirect_to request.referrer
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_comment.html.erb
<%= content_tag "div", id: comment.id, class: "media" do %>
		<h4><%= comment.author.username %>, <%= distance_of_time_in_words_to_now(comment.created_at) %> ago</h4>
		<div class="media-left">
			<%= vote_badge(comment) %>
		</div>
		<div class="media-body">
		<%= comment.content %>
		<br>
		<%= link_to "Permalink", comment_url(comment.id) %>
		<%= link_to "Reply", new_post_comment_url(comment.post_id, parent_comment_id: comment.id, redirect: request.url) %>
		<% unless comments_hash[comment.id].nil? %>
			<div class="nested-comment">
				<%= render comments_hash[comment.id], comments_hash: comments_hash %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/comments/_form.html.erb
<% default_grid do %>
		<h4>Add a comment!</h4>
		<%= form_for comment do |f| %>
			<%= f.hidden_field :parent_comment_id, value: parent_comment_id %>
			<%= f.hidden_field :redirect, value: redirect %>
			<%= f.hidden_field :post_id, value: post_id %>
			<div class="form-group"> 
				<%= f.text_area :content, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.submit "Submit", class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/comments/edit.html.erb
<div class="row">
	<div class="col-xl-6 col-xs-offset-3">
		<h1>Editing: <%= @comment.title %>!</h1>
		<%= render 'comments/form', 
			comment: @comment, 
			parent_comment_id: params[:parent_comment_id], 
			redirect: params[:redirect],
			post_id: params[:post_id] 
		%>
	</div>
</div>

app/views/comments/new.html.erb
<h1>Write a comment!
<%= render 'comments/form', 
	comment: Comment.new, 
	parent_comment_id: params[:parent_comment_id], 
	redirect: params[:redirect],
	post_id: params[:post_id] 
%>

app/views/comments/show.html.erb
<h2>By <%= @comment.author.username %></h2>
<p><%= @comment.content %></p>
<% comments_hash = @comment.child_comments_by_parent_id %>
<% if comments_hash %>
	<h3>Responses</h3>
	<%= render comments_hash[@comment.id], comments_hash: comments_hash %>
<% end %>
<%= render 'comments/form', 
  comment: Comment.new,
  parent_comment_id: @comment.id,
  post_id: @comment.post_id,
  redirect: comment_url(@comment)
%>