config/routes.rb
Rails.application.routes.draw do
  root to: "subs#index"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  
  resources :posts, except: [:index, :upvote, :downvote] do
    resources :comments, only: :new
    post "upvote", on: :member
    post "downvote", on: :member
  end
  
  resources :comments, only: [:show, :create, :destroy, :edit, :update] do
    post "upvote", on: :member
    post "downvote", on: :member
  end
  
  get 'static_pages/home'
  get 'static_pages/contact' 
  get 'static_pages/about'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user, :user_is_creator?
  
  def login!(user)
    session[:session_token] = user.session_token
  end
  
  def logout
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end
  
  def current_user
    User.find_by(session_token: session[:session_token])
  end
  
  def require_login
    redirect_to new_session_url if current_user.nil?
  end
  
  def user_is_creator?(object, id_name)
    user = current_user
    user ? (current_user.id == object.send(id_name)) : false
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logout_button
    form = "<div class=\"navbar-nav nav navbar-right\">"
    form +=  "<form action=\"/session\" method=\"post\" class=\"form-inline\">"
    form += "<div class=\"form-group\"><p class=\"navbar-text\">Logged in as #{current_user.username}</p></div>"
    form += "<input type=\"hidden\" value=\"DELETE\" name=\"_method\">"
    form += "<button value=\"Submit!\"  class=\"btn-default btn\">Sign Out</button>"
    form += "</form></div>"
    form.html_safe
  end
  
  def vote_buttons(object)
    obj_name = object.class.to_s.downcase
    
    upvote_path = send("upvote_#{obj_name}_path", object)
    upvote_span = content_tag("span", "", class: "glyphicon glyphicon-arrow-up")
    form = "<div class=\"btn-group\">"
    form += form_for(:upvote, url: upvote_path) do |f| 
      f.button(upvote_span, class: "btn btn-default btn-xs")
    end
    
    downvote_path = send("downvote_#{obj_name}_path", object)
    downvote_span = content_tag("span", "", class: "glyphicon glyphicon-arrow-down")
    form += form_for(:downvote, url: downvote_path) do |f|
      f.button(downvote_span, class: "btn btn-default btn-xs")
    end
    form += "</div>"
    form.html_safe
  end
  
  def vote_badge(object)
		number = content_tag("div", object.score, class: "btn-group")
    buttons = vote_buttons(object)
    "<div class=\"vote-badge\">#{number}#{buttons}</div>".html_safe
  end
  
  def edit_delete_buttons(object)
    obj_name = object.class.to_s.downcase
    edit_url = send("edit_#{obj_name}_url", object)
    edit_link = link_to("Edit", edit_url, class: "btn btn-default btn-xs")
    
    destroy_url = send("#{obj_name}_url", object)
    destroy_link = form_for(object, url: destroy_url, method: :delete, html: { class: "btn-group" }) do |f|
      f.button("Delete", class: "btn btn-default btn-xs")
    end
    
    (content_tag("div", edit_link, class: "btn-group") + destroy_link).html_safe
  end
  
  def default_grid(&blk)
    content_tag("div", class: "row") do
      content_tag("div", class: "col-xs-6 col-xs-offset-3", &blk)
    end
  end
  
end

app/views/application/_alerts.html.erb
<%= default_grid do %>
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<%= content_tag("div", error, class: "alert alert-danger") %>
		<% end %>
	<% end %>
	<% if flash[:successes] %>
		<% flash[:successes].each do |success| %>
			<%= content_tag("div", success, class: "alert alert-success") %>
		<% end %>
	<% end %>
<% end %>

app/views/application/_auth.html.erb
<%= default_grid do %>
	<h1><%= header %></h1>
	<%= form_for user, url: url do |f| %>
		<div class="form-group">
			<%= f.text_field :username, placeholder: 'Username', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit "Submit", class: "btn btn-primary" %>
		</div>
	<% end %>
<% end %>

app/views/application/_navbar.html.erb
<nav class='navbar navbar-default'>
	<div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
		  <%= link_to("MsgBoard", root_path, class: "navbar-brand")  %>
	    </div>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<% if current_user %>
		<ul class="navbar-nav nav">
			<li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Subs <span class="caret"></span></a>
			    <ul class="dropdown-menu" role="menu">
					<li><%= link_to "All subs", subs_url %></li>
					<li class="divider"></li>
					<% Sub.all.order(:title).each do |sub| %>
						<li><%= link_to sub.title, sub_url(sub) %></li>
					<% end %>
				</ul>
			</li>
			<li><%= link_to "Create a sub", new_sub_url %></li>
			<li><%= link_to "Make a post", new_post_url %></li>
		</ul>
		<%= logout_button %>
		<% else %>
			<ul class="navbar-nav nav">
			<li><%= link_to "Login", new_session_url %></li>
			<li><%= link_to "Create an account", new_user_url %></li>
			</ul>
		<% end %>
	</div>
	</div>
</nav>

app/views/application/_voting.html.erb
<%= button_to "upvote", action: "upvote" %>
<%= button_to "downvote", action: "downvote" %>